version: '3.1'

services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '80:8000'
    restart: "no"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: lollo
      MYSQL_PASSWORD: proof
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306' 
    volumes:
      - mydata:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  mydata:
